# 错误处理

go中错误分为两类，一类为可恢复错误，比如文件不存在等，属于外部错误；另一类为不可恢复错误，比如数组访问越界，通常是程序bug。

go使用类似于rust的可空类型处理可恢复错误。

一个可能发生错误的函数返回两个值，一个结果值，一个错误值。如果错误值不为空，则表明发生了错误。

```go

import "strconv"

func main() {
    s := "h"
    c, err := strconv.Atoi(s) // Atoi函数返回转换的结果值和错误值
    if err != nil {
        // error occured
        fmt.Println("Error: ")
        fmt.Println(err)
        return
    }
    fmt.Println(c)
}
// output
Error: 
strconv.Atoi: parsing "h": invalid syntax
```

go使用`panic`和`recover`处理不可恢复错误。

```go
func f(r int) {
    if r
}
```

